#!/bin/sh
################################################################################
# runit stage 3 script
################################################################################

export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/X11R6/bin

########################################

def_color="\\033[0;37m"		# light gray
msg_color="\\033[1;37m"		# white

term_color="\\033[1;34m"	# dark blue
dark_color="\\033[1;30m"	# dark gray
good_color="\\033[1;32m"	# light green
fail_color="\\033[1;31m"	# red

print_msg() {
	echo -e "${msg_color}${*}${def_color}"
	return 0
}

report_status() {
	echo -e -n "${term_color}"
	if ${*}; then
#>>>		sleep 2
		echo -e "${good_color}* ${dark_color}${*}${def_color}"
		return 0
	else
#>>>		sleep 2
		echo -e "${fail_color}* ${dark_color}${*}${def_color}"
		return 1
	fi
	return 0
}

countdown() {
	echo -e -n "${term_color}"
	for NUM in 5 4 3 2 1; do
		echo -e -n " ${NUM}"
		sleep 1
	done
	echo -e "${def_color}"
}

################################################################################

print_msg "Saving clock..."
report_status hwclock --debug --systohc --localtime

if [ -x "$(which alsamixer)" ]; then
	print_msg "Storing alsa state..."
	store_alsa_state() {
		RESULT="$(alsactl store -f /etc/asound.state)"
		if [ -n "${RESULT}" ]; then
			echo "${RESULT}"
			return 1
		fi
		return 0
	}
	report_status store_alsa_state
fi

print_msg "Syncing disks..."
report_status sync

print_msg "Sending TERM signal to all processes..."
report_status killall5 -15
countdown

print_msg "Sending KILL signal to all processes..."
report_status killall5 -9
countdown

print_msg "Syncing disks one last time..."
report_status sync

########################################

print_msg "Unmounting data filesystems..."
{
	report_status eval "HOME=/.g/.home /.g/.home/scripts/_sync mount x sda"		;
	report_status eval "HOME=/.g/.home /.g/.home/scripts/_sync mount x sdb"		;
} || {
	print_msg "${fail_color}!!! Data filesystems are not completely unmounted !!!"	;
	sleep 10									;
}

########################################

print_msg "Unmounting all filesystems..."
report_status umount -a -d -f -r -v
report_status umount -a -d -f -r -v

print_msg "Showing results..."
report_status eval "ps -ef | grep -vE \"[]]$\""
report_status cat /proc/mounts

print_msg "${fail_color}### System is down ###"
sleep 10

exit 0
################################################################################
# end of file
################################################################################
