#!/bin/sh
exec 2>&1
export HOME="/.g/.home"
killall -v -9 autossh
exec autossh \
	-M 0 \
	-T \
	-F ${HOME}/.ssh/config.batch \
	-i ${HOME}/.ssh/remote_id \
	-R 65532:127.0.0.1:22 \
	plastic@server.garybgenett.net
# end of file
