#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
sv start /.runit/services/dbus		|| exit 1
killall -v -9 bluetoothd
cat >/etc/bluetooth/main.conf <<END_OF_CONF
[General]
Name=Unknown Device
deviceID=bluetooth
END_OF_CONF
export PATH="/usr/libexec/bluetooth:${PATH}"
exec bluetoothd \
	--debug \
	--nodetach
# end of file
