#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/dbus		|| exit 1
sv start /.runit/services/pulseaudio	|| exit 1
export PATH="/usr/libexec/bluetooth:${PATH}"
cat >/etc/bluetooth/main.conf <<END_OF_CONF
[General]
Name=Unknown Device
deviceID=bluetooth
END_OF_CONF
killall -v -9 bluetoothd
mkdir -pv /var/lib/bluetooth
rm -frv /var/lib/bluetooth/*
exec bluetoothd \
	--debug \
	--nodetach
# end of file
