#!/bin/sh
# edit: /etc/cups/cupsd.conf
# add: AccessLog /dev/stdout
# add: ErrorLog /dev/stdout
# add: PageLog /dev/stdout
exec 2>&1
sv start /.runit/services/syslogd || exit 1
sv start /.runit/services/klogd || exit 1
killall -9 cupsd
exec cupsd \
	-f
# end of file
