#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
chmod -v 755 `which dbus-daemon`
chmod -v 755 `which dbus-launch`
killall -v -9 dbus-daemon
#>>>killall -v -9 dbus-launch
mkdir -pv /var/run/dbus
rm -frv /var/run/dbus.pid
exec dbus-daemon \
	--nofork \
	--system
# end of file
