#!/bin/sh
# edit: /etc/dbus-1/system.conf
# comment: <fork/>
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -9 dbus-daemon
killall -9 dbus-launch
rm -frv /var/run/dbus.pid
mkdir -pv /var/run/dbus
exec dbus-daemon \
	--system
# end of file
