#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 dhclient
cat >/etc/dhclient.conf <<END_OF_CONF
timeout 0;
interface "wlan0" {
	send host-name "$(hostname)";
	prepend domain-search "example.net", "f5net.com", "olympus.f5net.com", "pdsea.f5net.com", "es.f5net.com", "gbg.es.f5net.com";
	prepend domain-name-servers 127.0.0.1;
	request dhcp-server-identifier, host-name, subnet-mask, broadcast-address, routers, domain-name-servers, domain-name, domain-search, ntp-servers, time-offset, interface-mtu;
	require dhcp-server-identifier;
}
END_OF_CONF
exec dhclient \
	-v			\
	-d			\
	-cf /etc/dhclient.conf	\
	wlan0
# end of file
