#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 dhcpd
mkdir -pv /var/run/dhcp
rm -frv /var/run/dhcp/dhcpd.pid
mkdir -pv /var/lib/dhcp
rm -frv /var/lib/dhcp/*
touch /var/lib/dhcp/dhcpd.leases
exec dhcpd \
	-f \
	-d \
	br0 qemu0
# end of file
