#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 dhcpcd
rm -frv /var/lib/dhcp/*
cat >/etc/resolv.conf.head <<END_OF_CONF
search		example.net
nameserver	127.0.0.1
nameserver	10.255.255.254
nameserver	208.67.222.222
nameserver	208.67.220.220
END_OF_CONF
exec dhcpcd \
	--nobackground \
	--debug \
	--timeout 0 \
	--config /dev/null \
	--require dhcp_server_identifier \
	--option dhcp_server_identifier \
	--option domain_name_servers \
	--option domain_name \
	--option domain_search \
	--option ntp_servers \
	--option interface_mtu \
	--nooption host_name \
	--nohook lookup-hostname \
	--nohook hostname \
	--hostname \
	eth0
# end of file
