#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -9 dhcpd
rm -frv /var/run/dhcp/dhcpd.pid
mkdir -pv /var/lib/dhcp
touch /var/lib/dhcp/dhcpd.leases
exec dhcpd \
	-f	\
	-d
# end of file
