#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/xorg.null	|| exit 1
sv start /.runit/services/xsession.null	|| exit 1
export HOME_SRC="/.g/_data/zactive/.home"
export HOME="/tmp/.null"
export DISPLAY=":9"
#>>>killall -v -9 firefox
rm -frv ${HOME}/.mozilla
mkdir -pv ${HOME}/.mozilla/plugins
rsync -avv --delete --copy-links ${HOME_SRC}/.mozilla/plugins/ ${HOME}/.mozilla/plugins
chown -vR null:null ${HOME}/.mozilla
exec sudo -H -u null \
	firefox
# end of file
