#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd || exit 1
sv start /.runit/services/klogd || exit 1
sv start /.runit/services/dbus || exit 1
killall -9 hald
export DISPLAY=":0"
exec hald \
	--daemon=no
# end of file
