#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 hostapd
mkdir -pv /var/run/hostapd
chown -vR root:root /var/run/hostapd
exec hostapd \
	/etc/hostapd/hostapd.conf
# end of file
