#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 htc
htc \
	--forward-port 8889 \
	server.garybgenett.net:8888
PID="`pidof -s htc`"
while [ "`pidof -s htc`" -eq "${PID}" ]; do
	sleep 10
done
# end of file
