#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 hts
hts \
	--forward-port 127.0.0.1:22 \
	8888
PID="`pidof -s hts`"
while [ "`pidof -s hts`" -eq "${PID}" ]; do
	sleep 10
done
# end of file
