#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -9 lighttpd
rm -frv /var/run/lighttpd/lighttpd.pid
mkdir -pv /var/run/lighttpd
chown -vR nobody:nobody /var/run/lighttpd
exec lighttpd \
	-D				\
	-f /etc/lighttpd/lighttpd.conf
# end of file
