#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 named
rm -frv /var/run/named/named.pid
mkdir -pv /var/run/named
chown -vR nobody:nobody /var/run/named
exec named \
	-f		\
	-u nobody
# end of file
