#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 named
mkdir -pv /var/run/named
rm -frv /var/run/named/named.pid
chown -vR nobody:nobody /var/run/named
exec named \
	-f \
	-u nobody
# end of file
