#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 nginx
rm -frv /var/lock/nginx.lock
rm -frv /var/run/nginx.pid
exec nginx \
	-g "daemon off;"
# end of file
