#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
# edit: /etc/ntp.conf
# set: logfile /dev/stdout
killall -v -9 ntpd
mkdir -pv /var/run/ntpd
ntpdate -v -b pool.ntp.org
exec ntpd \
	--nofork			\
	--logfile="/dev/stdout"
# end of file
