#!/bin/sh
# edit: /etc/ntp.conf
# set: logfile /dev/stdout
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -9 ntpd
mkdir -pv /var/run/ntpd
exec ntpd \
	--nofork			\
	--logfile="/dev/stdout"
# end of file
