#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
pkill -9 -f "nxproxy -S"
export DISPLAY=":0"
export NXPROXY_CMD="$(which nxproxy)"
exec sudo \
	-H			\
	-u \#1000		\
	${NXPROXY_CMD} \
		-S			\
		connect=127.0.0.1	\
		port=4009		\
		root=/tmp		\
		encryption=0		\
		cleanup=0		\
		timeout=0		\
		taint=1			\
		delta=1			\
		data=1			\
		stream=1		\
		strict=1		\
		cups=1			\
		smb=1
# end of file
