#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd || exit 1
sv start /.runit/services/klogd || exit 1
sv start /.runit/services/dbus || exit 1
sv start /.runit/services/hald || exit 1
sv start /.runit/services/pulseaudio || exit 1
sv start /.runit/services/xdm || exit 1
killall -9 pavucontrol
export DISPLAY=":0"
export PAVUCONTROL_CMD="$(which pavucontrol)"
exec sudo \
	-H			\
	-u \#1000		\
	${PAVUCONTROL_CMD}
# end of file
