#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd		|| exit 1
sv start /.runit/services/pulseaudio		|| exit 1
if [ -n "`pgrep -f "Xorg :9"`" ]; then
	sv start /.runit/services/xorg.null	|| exit 1
	export DISPLAY=":9"
else
	sv start /.runit/services/xorg		|| exit 1
	export DISPLAY=":0"
fi
killall -9 pavucontrol
exec sudo -H -u \#1000 \
	pavucontrol
# end of file
