#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 proftpd
mkdir -pv /var/run/proftpd
rm -frv /var/run/proftpd/proftpd.pid
exec proftpd \
	--nodaemon \
	--debug 1
# end of file
