#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 sshd
rm -frv /var/run/sshd.pid
[ ! -f /etc/ssh/ssh_host_dsa_key ] && ssh-keygen -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
[ ! -f /etc/ssh/ssh_host_rsa_key ] && ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
exec /usr/sbin/sshd \
	-D	\
	-e
# end of file
