#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
if [ ! -f /etc/ssh/ssh_host_ecdsa_key ]; then
	ssh-keygen -N "" -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_key
fi
killall -v -9 sshd
rm -frv /var/run/sshd.pid
exec sshd \
	-D \
	-e
# end of file
