#!/bin/sh
exec 2>&1
killall -v -9 syslogd
rm -frv /var/run/syslogd.pid
cat >/tmp/syslog.conf <<END_OF_CONF
# everything
*.*		/dev/stdout
# emergency messages
*.emerg		*
END_OF_CONF
exec syslogd \
	-n			\
	-f /tmp/syslog.conf	\
	-m 0
# end of file
