#!/bin/sh
exec 2>&1
cat >/tmp/syslog.conf <<END_OF_CONF
# everything
*.*		/dev/stdout
# emergency messages
*.emerg		*
END_OF_CONF
killall -v -9 syslogd
rm -frv /var/run/syslogd.pid
exec syslogd \
	-F \
	-f /tmp/syslog.conf \
	-s -s \
	-n \
	-m 0
# end of file
