#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
export TASKDDATA="/.g/_data/zactive/_pim/taskd"
export TASKD_PID="/var/run/taskd.pid"
export TASKD_LOG="/dev/stdout"
export TASKD_SRV="server.example.net:53589"
if [ ! -d ${TASKDDATA} ]; then
	mkdir -pv ${TASKDDATA}
	/usr/bin/taskd init --debug --data "${TASKDDATA}"
	/usr/bin/taskd add --debug --data "${TASKDDATA}" org local
	/usr/bin/taskd add --debug --data "${TASKDDATA}" group local group
	/usr/bin/taskd add --debug --data "${TASKDDATA}" user local user
	touch "${TASKDDATA}/orgs/local/groups/group/config"
	exit 0
fi
killall -v -9 taskd
rm -frv ${TASKD_PID}
exec /usr/bin/taskd \
	server \
	--debug \
	--data "${TASKDDATA}" \
		--debug="on" \
		--ip.log="on" \
		--log="${TASKD_LOG}" \
		--root="${TASKDDATA}" \
		--pid.file="${TASKD_PID}" \
		--extensions="${TASKDDATA}" \
		--server="${TASKD_SRV}" \
		--server.cert="/.g/_data/zactive/.home/.openssl/server.example.net.crt" \
		--server.key="/.g/_data/zactive/.home/.openssl/server.example.net.key" \
		--server.crl="/.g/_data/zactive/.home/.openssl/server-ca.example.net.crl" \
		--ca.cert="/.g/_data/zactive/.home/.openssl/client-ca.example.net.crt" \
		--debug.tls="1" \
		--client.allow="^taskd,^task [1-9],^Mirakel [1-9]"
# end of file
