#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
export TASKDDATA="/.g/_data/zactive/_pim/taskd"
export TASKD_SSL="/.g/_data/zactive/.home/.openssl"
export TASKD_SCR="${TASKD_SSL}/server.garybgenett.net.crt"
export TASKD_SKY="${TASKD_SSL}/server.garybgenett.net.key"
export TASKD_SRL="${TASKD_SSL}/server-ca.garybgenett.net.crl"
export TASKD_CCR="${TASKD_SSL}/client-ca.garybgenett.net.crt"
export TASKD_PID="/var/run/taskd.pid"
export TASKD_LOG="/dev/stdout"
export TASKD_SRV="0.0.0.0:53589"
export TASKD_CMD="`which taskd`"
if [ ! -d ${TASKDDATA} ]; then
	mkdir -pv ${TASKDDATA}
	/usr/bin/taskd init --debug --data="${TASKDDATA}"
	/usr/bin/taskd add --debug --data="${TASKDDATA}" org local
	/usr/bin/taskd add --debug --data="${TASKDDATA}" group local group
	/usr/bin/taskd add --debug --data="${TASKDDATA}" user local user
	touch "${TASKDDATA}/orgs/local/groups/group/config"
fi
cat /dev/null >"${TASKDDATA}/config"
killall -v -9 taskd
rm -frv ${TASKD_PID}
exec ${TASKD_CMD} \
	server \
	--debug \
	--pid.file="${TASKD_PID}" \
	--log="${TASKD_LOG}" \
	--data="${TASKDDATA}" \
		--verbose="on" \
		--debug="on" \
		--ip.log="on" \
		--root="${TASKDDATA}" \
		--extensions="${TASKDDATA}" \
		--server="${TASKD_SRV}" \
		--server.cert="${TASKD_SCR}" \
		--server.key="${TASKD_SKY}" \
		--server.crl="${TASKD_SRL}" \
		--ca.cert="${TASKD_CCR}" \
		--debug.tls="1" \
		--trust="strict" \
		--client.allow="^taskd,^task" \
		--confirmation="on" \
		--queue.size="1" \
		--request.limit="16777216" # (2^20)*(2^8) = 268435456 / (2^20)*(2^4) = 16777216 / default: (2^20) = 1048576
# end of file
