#!/bin/sh
exec 2>&1
killall -v -9 tcpdump
export TCPDUMP_DIR="/.runit/services/tcpdump/log"
export TCPDUMP_INT="eth0"
exec tcpdump \
	-i ${TCPDUMP_INT} \
	-w ${TCPDUMP_DIR}/tcpdump.${TCPDUMP_INT}. \
	-C 10 \
	-W 100 \
	-s 0
# end of file
