#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 in.tftpd
exec in.tftpd \
	--foreground \
	--verbose \
	--port-range 1069:1069 \
	--user nobody \
	--secure \
	/.g/_data/.store
# end of file
