#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -9 thttpd
exec thttpd \
	-D			\
	-l /dev/stdout		\
	-C /dev/null		\
	-u nobody		\
	-d /.g/_data/.www	\
	-c \*\*.cgi		\
	-v
# end of file
