#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
export UDEVD_BIN="udevd"
export UDEVD_CMD="`which ${UDEVD_BIN}`"
if [ ! -x "${UDEVD_CMD}" ]; then
	UDEVD_BIN="systemd-udevd"
	UDEVD_CMD="/lib/systemd/${UDEVD_BIN}"
fi
killall -v -9 ${UDEVD_BIN}
mkdir -pv -m 0755 /dev/.udev
exec ${UDEVD_CMD} \
	--debug
# end of file
