#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
UBAS="udevd"
UBIN="/sbin/${UBAS}"
if [ ! -x ${UBIN} ]; then
	UBAS="systemd-udevd"
	UBIN="/lib/systemd/${UBAS}"
fi
killall -v -9 ${UBAS}
mkdir -pv -m 0755 /dev/.udev
exec ${UBIN} \
	--debug
# end of file
