#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
export PATH="/lib/systemd:${PATH}"
killall -v -9 systemd-udevd
mkdir -pv -m 0755 /dev/.udev
exec systemd-udevd \
	--debug
# end of file
