#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
upsdrvctl stop
killall -v -9 usbhid-ups
killall -v -9 upsd
rm -frv /var/lib/nut/upsd.pid
mkdir -pv /var/lib/nut
chown -vR nut:nut /var/lib/nut
usermod -a -G usb nut
upsdrvctl start
exec upsd \
	-D \
	-u nut
# end of file
