#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv stop upsmon
killall -v -9 upsmon .nutmon.sh
upsdrvctl stop
killall -v -9 usbhid-ups
killall -v -9 upsd
mkdir -pv /var/lib/nut
rm -frv /var/lib/nut/upsd.pid
chown -vR nut:nut /var/lib/nut
usermod -a -G usb nut
upsdrvctl start
sv restart upsmon
exec upsd \
	-D \
	-u nut
# end of file
