#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/xorg.null	|| exit 1
sv start /.runit/services/xsession.null	|| exit 1
#>>>killall -v -9 vlc
export HOME="/tmp/.null"
export HOME_SRC="/.g/_data/zactive/.home"
export DISPLAY=":9"
export VLC_CMD="$(which vlc)"
for DIR in .config/vlc .local/share/vlc; do
	rm -frv ${HOME}/${DIR}
	mkdir -pv ${HOME}/${DIR}
	rsync -avv --delete --copy-links ${HOME_SRC}/${DIR}/ ${HOME}/${DIR}
	chown -vR null:null ${HOME}/${DIR}
done
exec sudo -H -u null \
	${VLC_CMD} \
		-I dummy \
		${HOME_SRC}/setup/_misc/playlist.m3u
# end of file
