#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd		|| exit 1
sv start /.runit/services/klogd			|| exit 1
sv start /.runit/services/xorg.null		|| exit 1
sv start /.runit/services/xsession.null		|| exit 1
#>>>killall -v -9 vlc
export HOME="/tmp/.null"
export HOME_SRC="/.g/_data/zactive/.home"
export DISPLAY=":9"
export VLC_CMD="$(which vlc)"
rm -frv ${HOME}/.config/vlc
mkdir -pv ${HOME}/.config/vlc
rsync -avv --delete --copy-links ${HOME_SRC}/.config/vlc/ ${HOME}/.config/vlc
chown -vR null:null ${HOME}/.config/vlc
exec sudo \
	-H		\
	-u null		\
	${VLC_CMD} \
		${HOME_SRC}/setup/_misc/playlist.m3u
# end of file
