#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
killall -v -9 wpa_supplicant
cat >/etc/wpa_supplicant/wpa_supplicant.conf <<END_OF_CONF
ap_scan=1
network={
	ssid="Unknown Network"
#>>>	ssid="Invalid Network"
#>>>	ssid="Unsafe Network"
	psk="onthenetwork"
	key_mgmt=WPA-PSK
	scan_ssid=1
	priority=99
}
#>>>network={
#>>>	ssid="InternetConnection"
#>>>	psk="MustGoFaster"
#>>>	key_mgmt=WPA-PSK
#>>>	scan_ssid=1
#>>>	priority=98
#>>>}
END_OF_CONF
if [ ! -e /tmp/.wpa_supplicant.conf ]; then
cat >/tmp/.wpa_supplicant.conf <<END_OF_CONF
network={
	ssid="Sun Rae"
	psk="*Pr1v8 Netw0rk*"
	key_mgmt=WPA-PSK
	scan_ssid=1
	priority=19
}
network={
	ssid="spl-public"
	scan_ssid=1
	priority=18
}
END_OF_CONF
fi
cat /tmp/.wpa_supplicant.conf >>/etc/wpa_supplicant/wpa_supplicant.conf
exec wpa_supplicant \
	-d \
	-t \
	-f /dev/stdout \
	-c /etc/wpa_supplicant/wpa_supplicant.conf \
	-D nl80211 \
	-i wlan0
# end of file
