#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/xorg.null	|| exit 1
sv start /.runit/services/xsession.null	|| exit 1
export DISPLAY=":9"
export LC_NUMERIC="C"
killall -v -9 xbmc
killall -v -9 xbmc.bin
exec sudo -H -u \#1000 \
	xbmc
# end of file
