#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 xdm
rm -frv /var/run/xdm.pid
export X_CMD="$(which X)"
exec xdm \
	-nodaemon \
	-error /dev/stderr \
	-server ":0 local ${X_CMD} -keeptty -logfile /dev/stderr -nolisten tcp"
# end of file
