#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
kill -9 $(pgrep -f "Xorg :0")
rmmod -v nvidia
modprobe -v nvidia
export XORG_CMD="$(which Xorg)"
exec ${XORG_CMD} \
	:0			\
	tty5			\
	-keeptty		\
	-logfile /dev/stderr	\
	-nolisten tcp
# end of file
