#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 xpra
exec sudo -H -u \#1000 \
	xpra \
		start \
		--daemon=no \
		--debug=server+keyboard \
		--chdir=/tmp/xpra \
		--socket-dir=/tmp/xpra \
		--remote-logging=no \
		--desktop-scaling=auto \
		--window-close=disconnect \
		--exit-ssh=yes \
		--html=off \
		--xsettings=no \
		--system-tray=no \
		--tray=yes \
		--bell=no \
		--input-method=xim \
		--keyboard-sync=no \
		--clipboard=yes \
		--clipboard-direction=both \
		--file-transfer=off \
		--pulseaudio=no \
		--speaker=off \
		--microphone=off \
		:1
# end of file
