#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
sv start /.runit/services/xorg		|| exit 1
export HOME="/.g/_data/zactive/.home"
export SHELL="/bin/bash"
export DISPLAY=":0"
export WM_CMD="${HOME}/commands/dwm"
#>>>export WM_CMD="$(which openbox) --replace"
sudo \
	-H		\
	-u \#1000	\
	${WM_CMD} &
exec sudo \
	-H		\
	-u \#1000	\
	${HOME}/.xsession
# end of file
