#!/bin/sh
exec 2>&1
sv start /.runit/services/xorg || exit 1
export HOME="/dev/null"
export SHELL="/bin/bash"
export DISPLAY=":0"
export OPENBOX_CMD="$(which openbox)"
xset -dpms
xset s off
exec sudo \
	-H			\
	-u nobody		\
	${OPENBOX_CMD} \
		--replace
# end of file
