#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
sv start /.runit/services/klogd		|| exit 1
sv start /.runit/services/xorg		|| exit 1
sleep 3
export HOME="/.g/_data/zactive/.home"
export SHELL="/bin/bash"
export DISPLAY=":0"
exec sudo -H -u \#1000 \
	${HOME}/.xsession
# end of file
