#!/bin/sh
exec 2>&1
sv start /.runit/services/xorg		|| exit 1
export HOME="/tmp/.null"
export DISPLAY=":0"
export OPENBOX_CMD="$(which openbox)"
mkdir -pv ${HOME}/.config/openbox
cat >${HOME}/.config/openbox/rc.xml <<END_OF_CONF
<?xml version="1.0" encoding="utf-8"?>
<openbox_config>
</openbox_config>
END_OF_CONF
xset -dpms
xset b off
xset s off
exec sudo \
	-H			\
	-u null			\
	${OPENBOX_CMD} \
		--replace
# end of file
