#!/bin/sh
exec 2>&1
sv start /.runit/services/xorg || exit 1
export HOME="/.g/_data/zactive/.home"
export DISPLAY=":0"
export OPENBOX_CMD="$(which openbox)"
sudo \
	-H			\
	-u \#1000		\
	${OPENBOX_CMD} \
		--replace &
exec sudo \
	-H			\
	-u \#1000		\
	${HOME}/.xsession
# end of file
