#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
export HOME="/.g/_data/zactive/.home"
killall -v -9 Xvfb
#>>>			-screen 0 1366x768x24
exec sudo -H -u \#1000 \
	xinit \
		${HOME}/.xsession \
		-- \
		Xvfb \
			:1 \
			-nolisten tcp \
			-screen 0 1280x1024x24
# end of file
