#!/bin/sh
exec 2>&1
sv start /.runit/services/syslogd	|| exit 1
killall -v -9 Xvfb
export HOME="/.g/_data/zactive/.home"
export SHELL="/bin/bash"
export XINIT_CMD="$(which xinit)"
export XVFB_CMD="$(which Xvfb)"
exec sudo -H -u \#1000 \
	${XINIT_CMD} \
		${HOME}/.xsession \
		-- \
		${XVFB_CMD} \
			:1 \
			-nolisten tcp \
			-screen 0 1280x1024x24
#>>>			-screen 0 1366x768x24
# end of file
