#!/bin/sh
exec 2>&1
killall -9 Xvfb
export HOME="/.g/_data/zactive/.home"
export XINIT_CMD="$(which xinit)"
export XVFB_CMD="$(which Xvfb)"
exec sudo \
	-H			\
	-u \#1000		\
	${XINIT_CMD} \
		${HOME}/.xsession \
		-- \
		${XVFB_CMD} \
			:1			\
			-screen 0 1440x900x24
# end of file
